# Generated by Django 6.0.5 on 2026-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned'), ('archived', 'Archived')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('architecture', models.TextField(blank=True)),
                ('stack', models.JSONField(default=list, help_text="['Django', 'Docker']")),
                ('highlights', models.JSONField(default=list, help_text="['JWT Auth', 'Multi-tenant']")),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
