# Generated by Django 6.0.5 on 2026-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('horizon', models.CharField(choices=[('short', 'Short Term'), ('medium', 'Medium Term'), ('long', 'Long Term')], max_length=10)),
                ('target_date', models.CharField(help_text='Ex: Q2 2026, 2027', max_length=50)),
                ('done', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['horizon', 'order'],
            },
        ),
    ]
