# Generated by Django 6.0.5 on 2026-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.JSONField(default=list)),
                ('content', models.TextField(help_text='Markdown — notes, erreurs, découvertes')),
                ('obsidian_file', models.CharField(blank=True, max_length=500)),
                ('published', models.BooleanField(default=True)),
                ('entry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
