# Generated by Django 6.0.5 on 2026-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('planned', 'Planned')], default='draft', max_length=20)),
                ('tags', models.JSONField(default=list, help_text="['Docker', 'AWS', 'Nginx']")),
                ('objective', models.TextField(help_text='Ce que tu voulais accomplir')),
                ('stack', models.CharField(max_length=300)),
                ('architecture', models.TextField(blank=True)),
                ('problems_encountered', models.TextField(blank=True)),
                ('lessons_learned', models.JSONField(default=list)),
                ('content', models.TextField(blank=True, help_text='Markdown complet — étapes, code, screenshots')),
                ('obsidian_file', models.CharField(blank=True, help_text='Chemin relatif dans le vault : walkthroughs/aws-ec2.md', max_length=500)),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
