# Generated by Django 4.2.30 on 2026-08-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        ('walkthroughs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walkthrough',
            options={'ordering': ['published_at', 'created_at']},
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='source_note',
            field=models.ForeignKey(blank=True, help_text='La note brute dont ce walkthrough est issu, si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='became_walkthroughs', to='journal.journalentry'),
        ),
    ]
