# Generated by Django 6.0.5 on 2026-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Ex: devicon-docker-plain', max_length=100)),
                ('level', models.PositiveIntegerField(default=0, help_text='0 à 100')),
                ('category', models.CharField(choices=[('current', 'Current'), ('learning', 'Learning'), ('future', 'Future')], default='current', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
